### ISSUE TITLE
/doc must have required property version

### ISSUE THREAD

**Issue by tfriedel** [MarkMendell/cpwrap#1]
I just tried it using the most up to date copilot neovim plugin, but it wouldn't autocomplete, both in "sh" and in "python".
I then compiled it with verbose flags set and these were the last messages it showed:

```
writing to copilot:
{"params":{"textDocument":{"uri":"file:\/\/\/tmp\/shell_session.txt","languageId":"sh","relativePath":"\/tmp\/shell_session.txt"},"doc":{"languageId":"sh","relativePath":"\/tmp\/shell_session.txt","uri":"file:\/\/\/tmp\/shell_session.txt","insertSpaces":false,"position":{"character":4,"line":3},"path":"\/tmp\/shell_session.txt","indentSize":2,"tabSize":2,"source":"Python 2.7.18 (default, Jul  1 2022, 12:27:04) \n[GCC 9.4.0] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> "},"position":{"character":4,"line":3}},"id":4,"method":"getCompletions","jsonrpc":"2.0"}
trying to get a message from copilot with id 4
filling for content-length
read copilot: EAGAIN
waiting for transcript/copilot
trying to get a message from copilot with id 4
filling for content-length
filling for content-length #
content-length: 119
filling for \r\n\r\n
filling for message (0/119)
read copilot: EAGAIN
waiting for transcript/copilot
trying to get a message from copilot with id 4
filling for content-length
content-length: 119
filling for \r\n\r\n
filling for message (0/119)

msg from copilot:
{"jsonrpc":"2.0","id":4,"error":{"code":-32602,"message":"Invalid params: /doc must have required property 'version'"}}
waiting for transcript to change
poll returned: 0 0 0 1 (POLLIN=1, POLLOUT=4, POLLERR=8, POLLHUP=16)
waiting on poll (0 0)...
```

**Comment by MarkMendell** [comment]
Thanks, looks like something changed. Reverting to version 1.7.0 works.

I'm thinking we just need to add whatever 'version' is in the "doc" object.

For completions sake, if I capture the output of 1.7.0 vs 1.8.2 in neovim:
1. `method: initialize` no difference
2. `method: textDocument/didOpen` no difference (we don't send this one anyway)
3. `method: setEditorInfo`  
    1. `params.editorConfiguration`
        1. `.disabledLanguages`:
old: `[".", "cvs", "gitcommit", "gitrebase", "help", "hgcommit", "markdown", "svn", "yaml"]`  
new: `{"languageId":"."},{"languageId":"cvs"},{"languageId":"gitcommit"},{"languageId":"gitrebase"},{"languageId":"help"},{"languageId":"hgcommit"},{"languageId":"markdown"},{"languageId":"svn"},{"languageId":"yaml"}`
        1. `.enableAutoCompletions` old: `1`, new: `true`
    1. but we don't send the `editorConfiguration` field anyway
4. `method: textDocument/didChange` no difference (we don't send)
5. `method: getCompletions`
    1. `params.doc.languageId` removed
    2. `params.doc.path` removed
    3. `params.doc.source` removed **!!!**
    4. `params.doc.version` added
    5. `params.textDocument.version` added

Looks like `version` is a number that just increments. I used `vtranscriptcopy` for `params.doc.version`, but now I get:
```
{"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [getCompletions] [2023-02-05T18:06:56.223Z] Producing empty completions due to document version mismatch. Completions requested for document version 2 but document version was 0.","metadataStr":"[DEBUG] [getCompletions] [2023-02-05T18:06:56.223Z]","extra":["Producing empty completions due to document version mismatch. Completions requested for document version 2 but document version was 0."]}}
```

I was sending version 2, but it expected 0. I did a naive `vtranscriptcopy-2` and got back a completion. But then after typing, it gave the same message saying it expected version to be 0. So I just set it to 0 and now it works.

It seems like the vim plugin has moved away from sending the source in every request, and instead sends a change of what happened. As long as they still allow us sending the full source, we'll just keep with that.

Fixed
